data:
  raw_path: 'data/raw/diabetic_data.csv'
  processed_train_path: 'data/processed/train.csv'
  processed_test_path: 'data/processed/test.csv'
  dataset_url: 'https://archive.ics.uci.edu/ml/machine-learning-databases/00296/dataset_diabetes.zip'

params:
  test_size: 0.2
  random_state: 42
  
  skope_rules:
    n_estimators: 30
    max_samples: 0.8
    max_depth_duplication: 2