data:
  raw_path: 'data/raw/diabetic_data.csv'
  processed_train_path: 'data/processed/train.csv'
  processed_test_path: 'data/processed/test.csv'
  dataset_url: 'https://archive.ics.uci.edu/ml/machine-learning-databases/00296/dataset/diabetes.zip'