data:
  raw_path: 'data/raw/diabetic_data.csv'
  processed_train_path: 'data/processed/train.csv'
  processed_test_path: 'data/processed/test.csv'
  dataset_url: 'https://archive.ics.uci.edu/ml/machine-learning-databases/00296/dataset_diabetes.zip'

models:
  interpretable_model_path: 'models/skope_rules_model.pkl'
  constraints_path: 'models/domain_constraints.json'
  refined_model_path: 'models/refined_skope_rules_model.pkl'
  teacher_model_path: 'models/lightgbm_teacher.pkl'
  hybrid_model_path: 'models/hybrid_decision_tree.pkl'

params:
  test_size: 0.2
  random_state: 42

  skope_rules:
    n_estimators: 30
    max_samples: 0.8
    max_depth_duplication: 2
  
  lightgbm:
    n_estimators: 100
    learning_rate: 0.1
  
  decision_tree:
    max_depth: 4